-- Database: red_emprendedora_db

-- DROP DATABASE IF EXISTS red_emprendedora_db;

CREATE DATABASE red_emprendedora_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL,
    ID_USUARIO_ROL CONSTRAINT FK_USUARIO_ROL REFERENCES USUARIO_ROL(ID_USUARIO_ROL)
    ID_EVENTO CONSTRAINT FK_EVENTO_USUARIO REFERENCES EVENTO(ID_EVENTO)
    ID_LOCALIDAD CONSTRAINT FK_LOCALIDAD_USUARIO REFERENCES LOCALIDAD(ID_LOCALIDAD)
    NOMBRE_EMPRENDIMIENTO VARCHAR(100),
    TIPO_EMPRENDIMIENTO VARCHAR(100),
    INSTAGRAM VARCHAR(100)
);