-- Database: red_emprendedora_db

-- DROP DATABASE IF EXISTS red_emprendedora_bd;

CREATE DATABASE red_emprendedora_bd
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE EVENTO (
    ID_EVENTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR (50) NOT NULL,
    FECHA_INICIO VARCHAR (25) NOT NULL,
    FECHA_FIN VARCHAR (25) NOT NULL,
    ESTADO VARCHAR (50) NOT NULL,
    PRECIO_ENTRADA NUMERIC(10, 2) NOT NULL,
    METROS_CUADRADOS VARCHAR (25) NOT NULL
); 

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL,
    NOMBRE_EMPRENDIMIENTO VARCHAR(100),
    TIPO_EMPRENDIMIENTO VARCHAR(100),
    INSTAGRAM VARCHAR(100)
);

CREATE TABLE USUARIO_ROL (
    ID_USUARIO_ROL SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE LOCALIDAD (
    ID_LOCALIDAD SERIAL PRIMARY KEY,
    NOMBRE_LOCALIDAD VARCHAR(50) NOT NULL,
    PROVINCIA_LOCALIDAD VARCHAR(50) NOT NULL
);
CREATE TABLE STAND (
    ID_STAND SERIAL PRIMARY KEY,
    COSTO_STAND DECIMAL(10,2),
    ESTADO_STAND BOOLEAN NOT NULL,
    NUMERO_STAND INTEGER NOT NULL
);

ALTER TABLE EVENTO
ADD COLUMN ID_LOCALIDAD INT;

ALTER TABLE EVENTO
ADD CONSTRAINT FK_LOCALIDAD
FOREIGN KEY (id_localidad)
REFERENCES LOCALIDAD(id_localidad);

ALTER TABLE EVENTO
ADD COLUMN ID_USUARIO INT;

ALTER TABLE EVENTO
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE USUARIO
ADD COLUMN ID_USUARIO_ROL INT;

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_ROL
FOREIGN KEY (ID_USUARIO_ROL)
REFERENCES USUARIO_ROL (ID_USUARIO_ROL);

ALTER TABLE USUARIO
ADD COLUMN ID_EVENTO INT;

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_EVENTO
FOREIGN KEY (ID_EVENTO)
REFERENCES EVENTO (ID_EVENTO);

ALTER TABLE USUARIO
ADD COLUMN ID_LOCALIDAD INT;

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_LOCALIDAD
FOREIGN KEY (ID_LOCALIDAD)
REFERENCES LOCALIDAD (ID_LOCALIDAD);

ALTER TABLE USUARIO_ROL
ADD COLUMN ID_USUARIO INT;

ALTER TABLE USUARIO_ROL
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE LOCALIDAD
ADD COLUMN ID_USUARIO INT;

ALTER TABLE LOCALIDAD
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE LOCALIDAD
ADD COLUMN ID_EVENTO INT;

ALTER TABLE LOCALIDAD
ADD CONSTRAINT FK_EVENTO
FOREIGN KEY (ID_EVENTO)
REFERENCES EVENTO (ID_EVENTO);

ALTER TABLE STAND 
ADD COLUMN ID_EVENTO INT;
ALTER TABLE STAND 
ADD CONSTRAINT fk_stand_evento 
FOREIGN KEY (ID_EVENTO) 
REFERENCES EVENTO (ID_EVENTO);

ALTER TABLE STAND 
ADD COLUMN ID_USUARIO INT;
ALTER TABLE STAND 
ADD CONSTRAINT fk_stand_usuario 
FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO (ID_USUARIO);